version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0.362
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle build
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

  build-and-deploy-to-prod:
    docker:
      - image: cimg/openjdk:8.0.362
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run: gradle bootJar
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - add_ssh_keys
      #          fingerprints:
      #            - "${SSH_FINGERPRINT}"
      #- run: ssh-keyscan -H ${SSH_SERVER} >> ~/.ssh/known_hosts
      - run:
          name: Deploy Over SSH
          command: |
            echo '${SSH_KNOWN_HOST}' >> ~/.ssh/known_hosts
            scp -o StrictHostKeyChecking=no -P ${SSH_PORT} -r ~/repo/build/libs/*.jar ${SSH_USER}@${SSH_HOST}:~/circleciuploads/vatsim-fleet/vatsim-fleet.jar

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: develop

  build-and-deploy-to-prod:
    jobs:
      - build-and-deploy-to-prod:
          filters:
            branches:
              only: prod
